[build]
builder = "nixpacks"

[build.env]
NPM_CONFIG_PRODUCTION = "false"

[nixpacks.phases.setup]
nixPkgs = ["nodejs", "npm"]

[nixpacks.phases.install]
cmds = [
  "rm -f package-lock.json",
  "npm install"
]

[nixpacks.phases.build]
cmds = ["npm run build"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = { default = "production" }
PORT = { default = "3001" }

# Health check configuration
[healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3

# Resource limits
[resources]
memory = 512
cpu = 0.5

# Networking
[networking]
serviceDomain = true